[2022-10-24T23:32:34.832+0200] {processor.py:154} INFO - Started process (PID=19183) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:34.833+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:32:34.835+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:34.835+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:34.854+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:34.853+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:32:34.854+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:34.854+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:32:34.854+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:34.864+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.040 seconds
[2022-10-24T23:32:40.059+0200] {processor.py:154} INFO - Started process (PID=19203) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:40.060+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:32:40.061+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:40.061+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:40.083+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:40.083+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:32:40.084+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:32:40.083+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:32:40.084+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:32:40.092+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2022-10-24T23:33:21.776+0200] {processor.py:154} INFO - Started process (PID=19596) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:33:21.779+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:33:21.781+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:33:21.781+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:33:21.803+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:33:21.802+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:33:21.804+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:33:21.803+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:33:21.804+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:33:21.816+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.044 seconds
[2022-10-24T23:34:05.165+0200] {processor.py:154} INFO - Started process (PID=19949) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:05.166+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:34:05.169+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:05.168+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:05.183+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:05.183+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:34:05.184+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:05.184+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:34:05.184+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:05.192+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2022-10-24T23:34:43.728+0200] {processor.py:154} INFO - Started process (PID=20239) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:43.731+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:34:43.733+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:43.733+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:43.754+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:43.754+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:34:43.754+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:34:43.754+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:34:43.755+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:34:43.764+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-10-24T23:35:24.712+0200] {processor.py:154} INFO - Started process (PID=20470) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:35:24.715+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:35:24.717+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:35:24.716+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:35:24.731+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:35:24.731+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:35:24.732+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:35:24.731+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:35:24.732+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:35:24.740+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2022-10-24T23:36:18.260+0200] {processor.py:154} INFO - Started process (PID=20900) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:18.271+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:36:18.274+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:18.273+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:18.331+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:18.330+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:36:18.331+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:18.331+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:36:18.331+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:18.366+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2022-10-24T23:36:57.600+0200] {processor.py:154} INFO - Started process (PID=21207) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:57.603+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:36:57.604+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:57.604+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:57.624+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:57.623+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:36:57.624+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:36:57.624+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:36:57.624+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:36:57.635+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2022-10-24T23:37:36.089+0200] {processor.py:154} INFO - Started process (PID=21365) to work on /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:37:36.091+0200] {processor.py:756} INFO - Processing file /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-10-24T23:37:36.092+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:37:36.092+0200] {dagbag.py:537} INFO - Filling up the DagBag from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:37:36.109+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:37:36.109+0200] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-10-24T23:37:36.110+0200] {logging_mixin.py:120} INFO - [2022-10-24T23:37:36.110+0200] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-10-24T23:37:36.110+0200] {processor.py:768} WARNING - No viable dags retrieved from /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-10-24T23:37:36.119+0200] {processor.py:176} INFO - Processing /home/batata/PycharmProjects/Restitution_python_test_de/test_de/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
